import Link from "next/link";
import { MarketingShell } from "@/components/marketing/marketing-shell";
import { StructuredData } from "@/components/marketing/structured-data";
import { breadcrumbSchema, marketingMetadata, SITE_ORIGIN } from "@/lib/seo";
import { serviceFaqs, servicePackages } from "@/lib/services";

export const metadata = marketingMetadata({ title: "Web Design, Development & Custom Software | Atheus", description: "Custom websites from £600, web development and bespoke software from independent UK studio Atheus. Explore scope, pricing, timelines and support.", path: "/services" });
export default function ServicesPage() {
  return <MarketingShell variant="agency">
    <StructuredData data={breadcrumbSchema([{ name: "Atheus", path: "/" }, { name: "Services", path: "/services" }])} />
    <StructuredData data={{ "@context": "https://schema.org", "@type": "Service", name: "Web design, development and custom software", url: `${SITE_ORIGIN}/services`, provider: { "@type": "Organization", name: "Atheus", url: SITE_ORIGIN }, areaServed: "United Kingdom" }} />
    <section className="agency-subhero"><div className="ax-container"><div className="agency-section-label"><span>Services / Atheus</span><span>From the first idea to the finished build</span></div><div className="agency-subhero-grid"><h1>Design with a point.<br /><em>Build with purpose.</em></h1><p>Strategy, art direction, interface design and development — shaped around what people need to understand, feel and do.</p></div></div></section>
    <section className="studio-service-disciplines ax-container"><article><span>01 / Design</span><h2>A distinct<br />point of view.</h2><p>Content structure, visual direction and interfaces shaped around your audience. Clear enough to use, distinctive enough to remember.</p></article><article><span>02 / Development</span><h2>Care in<br />the details.</h2><p>Responsive websites with accessible controls, purposeful motion and search foundations. The design carried through to the live experience.</p></article><article><span>03 / Software</span><h2>Ideas with<br />moving parts.</h2><p>Custom products, portals and data-driven tools. Interface and engineering considered together, from workflow to delivery.</p><Link href="/work/kickoff">See this in practice / KickOff ↗</Link></article></section>
    <section className="studio-pricing ax-container" id="pricing"><div className="agency-section-label"><span>Scope & investment</span><span>A clear agreement before work begins</span></div><div className="studio-pricing-heading"><h2>Know what<br /><em>you’re getting.</em></h2><p>These ranges explain the scale of a project. The final quote, deliverables and timeline are agreed around your brief.</p></div><div className="studio-package-list">{servicePackages.map((pack, index) => <article className="studio-package" key={pack.name}><div className="studio-package-title"><span>0{index + 1}</span><h3>{pack.name}</h3><strong>{pack.price}</strong></div><div><p>{pack.description}</p><ul>{pack.items.map((item) => <li key={item}>{item}</li>)}</ul><p className="studio-package-timing">{pack.timing}</p></div></article>)}</div><p className="studio-source">Core factual content and existing brand assets are supplied by you. Copywriting, asset production, hosting, domains and third-party services are scoped or priced separately.</p></section>
    <section className="studio-process"><div className="ax-container"><div className="agency-section-label"><span>How projects work</span><span>One point of contact</span></div><ol className="studio-flow">{[["Brief", "We agree the problem, audience, deliverables and scope."], ["Direction", "The content structure and visual language take shape."], ["Build", "The design becomes a responsive, working experience."], ["Launch", "We review, refine, launch and hand over the agreed assets."]].map(([title, description], index) => <li key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p><i aria-hidden="true">→</i></li>)}</ol></div></section>
    <section className="agency-faq"><div className="ax-container agency-faq-grid"><div><div className="agency-section-label"><span>The practical details</span></div><h2>Before<br /><em>we begin.</em></h2></div><div>{serviceFaqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>
    <section className="agency-offer"><div className="ax-container agency-offer-grid"><div><div className="agency-section-label"><span>Your brief / Next</span></div><h2>You don’t need<br /><em>all the answers.</em></h2></div><div className="agency-offer-aside"><p>A few details about the business, the idea and the timing are enough to start.</p><Link className="agency-btn" href="/contact">Start a project ↗</Link></div></div></section>
  </MarketingShell>;
}
