import type { Metadata } from "next";
import Image from "next/image";
import styles from "./lowrys.module.css";

const directions = "https://www.google.com/maps/search/?api=1&query=Lowrys+at+the+Chandlery+Berwick-upon-Tweed+TD15+1HE";
export const metadata: Metadata = {
  title: { absolute: "Lowry’s at the Chandlery — Design concept by Atheus" },
  description: "A proposed website direction for Lowry’s at the Chandlery. Design preview only; menu and visitor information await owner confirmation.",
  alternates: { canonical: "https://lowrys-preview.atheus.dev/" },
  robots: { index: false, follow: false, googleBot: { index: false, follow: false, noimageindex: true } },
  openGraph: { title: "Lowry’s at the Chandlery — A first look", description: "Warm quayside editorial. A website concept by Atheus, prepared for Lowry’s.", images: [{ url: "/previews/lowrys/chandlery.jpg", alt: "The Chandlery and the River Tweed, photographed by Geoff Holland" }] },
  twitter: { card: "summary_large_image", title: "Lowry’s — Design concept", description: "A proposed website direction by Atheus.", images: ["/previews/lowrys/chandlery.jpg"] },
};

export default function LowrysPreview() {
  return <div className={styles.site}>
    <a className={styles.skip} href="#main">Skip to content</a>
    <aside className={styles.preview}><span>ATHEUS × LOWRY’S</span><span>Design concept · Not the official website</span><a href="#concept-notes">About this preview ↗</a></aside>
    <header className={styles.header}>
      <a href="#" className={styles.wordmark} aria-label="Lowry’s at the Chandlery, top of page">Lowry’s<span>AT THE CHANDLERY</span></a>
      <nav aria-label="Main navigation"><a href="#menu">Menu</a><a href="#about">Our place</a><a href="#baking">Coffee & cake</a><a className={styles.visitLink} href="#visit">Find us <span aria-hidden="true">↗</span></a></nav>
    </header>
    <main id="main">
      <section className={styles.hero} aria-labelledby="hero-title">
        <div className={styles.heroCopy}><p className={styles.eyebrow}>An independent café on Berwick’s Quayside</p><h1 id="hero-title">A little time.<br /><em>By the Tweed.</em></h1><p className={styles.lede}>Homemade food, coffee and cake.<br />A warm welcome on Berwick’s historic quayside.</p><div className={styles.actions}><a className={styles.button} href="#menu">Explore the menu <span aria-hidden="true">↗</span></a><a className={styles.textLink} href="#visit">Plan a visit</a></div><div className={styles.heroFoot}><span>LOWRY’S AT THE CHANDLERY</span><span>Berwick-upon-Tweed<br />Northumberland</span></div></div>
        <figure className={styles.heroImage}><Image src="/previews/lowrys/chandlery.jpg" alt="The stone Chandlery building beside the River Tweed, with cobbled quayside in the foreground" width={1024} height={768} sizes="(max-width: 760px) 100vw, 55vw" preload /><figcaption>The Chandlery & the Tweed / A sense of place</figcaption><span className={styles.photoDate}>QUAYSIDE, BERWICK · 2023</span></figure>
      </section>
      <div className={styles.infoStrip}><span>Lunch at your own pace</span><span>Coffee, cake & baking</span><a href="#visit">Find us on the Quayside ↗</a></div>
      <section id="about" className={styles.intro}><p className={styles.eyebrow}>01 / Our place</p><h2>Off the quayside.<br /><em>Make yourself at home.</em></h2><div><p>A place to pause in Berwick-upon-Tweed. A catch-up over coffee, something for lunch, or a slice of cake after a wander by the river.</p><p>Lowry’s brings the café and the quayside together: familiar comforts, a relaxed setting, and time to enjoy both.</p><a className={styles.textLink} href="#visit">Come down to the Chandlery <span aria-hidden="true">↗</span></a></div></section>
      <section id="baking" className={styles.baking} aria-labelledby="baking-title"><div className={styles.bakingTitle}><p className={styles.eyebrow}>02 / Coffee, cake & baking</p><h2 id="baking-title">Always room<br />for <em>something sweet.</em></h2><p>A coffee and a catch-up. Tea and a slice.<br />The small pleasures worth making time for.</p></div><div className={styles.bakeryPrint} aria-label="Proposed coffee and baking feature"><span>AT THE CHANDLERY</span><p>Coffee.<br /><em>Cake.</em><br />Good company.</p><div className={styles.printRule} /><span>A LITTLE PAUSE, BY THE TWEED.</span></div><p className={styles.editorNote}>A place for Lowry’s own baking photography in the finished website.</p></section>
      <section id="menu" className={styles.menu} aria-labelledby="menu-title"><div className={styles.menuIntro}><p className={styles.eyebrow}>03 / At the table</p><h2 id="menu-title">Something<br /><em>to look forward to.</em></h2><p>A simple, readable menu, wherever you are.</p><p className={styles.menuNotice}>Menu design preview. Current dishes, prices and availability will be added from Lowry’s own menu.</p></div><div className={styles.menuPaper}><div className={styles.menuTop}><span>Lowry’s</span><span>THE MENU<br />A FIRST LOOK</span></div>{[
        ["01", "Lunch", "For a leisurely lunch", "This section will present Lowry’s current lunch menu, with clear descriptions and prices supplied by the café."],
        ["02", "Coffee & tea", "Put the kettle on", "A clear drinks list, with sizes and prices confirmed by Lowry’s."],
        ["03", "Cakes & baking", "Something sweet", "Space for the café’s baking selection and changing favourites, using owner-approved details and photography."],
      ].map(([number,title,subtitle,detail])=><details key={number} className={styles.menuItem}><summary><span>{number}</span><div><h3>{title}</h3><p>{subtitle}</p></div><b aria-hidden="true">+</b></summary><p className={styles.menuDetail}>{detail}</p></details>)}<p className={styles.menuBottom}>Dietary and allergen information to be confirmed with the café.</p></div></section>
      <section className={styles.river} aria-labelledby="river-title"><figure><Image src="/previews/lowrys/quayside.jpg" alt="Berwick’s historic quayside and riverside path beside the Tweed" width={4032} height={3024} sizes="(max-width: 760px) 100vw, 65vw" loading="eager" /><figcaption>Berwick’s Quayside / Photograph by Jonathan Hutchins, 2018</figcaption></figure><div className={styles.riverCopy}><p className={styles.eyebrow}>A café. A river. A little breathing room.</p><h2 id="river-title">Take the<br /><em>scenic route.</em></h2><p>Find us at the Chandlery on Berwick’s Quayside. Make Lowry’s part of your day by the Tweed.</p><a className={styles.button} href={directions} target="_blank" rel="noreferrer">Directions to Lowry’s <span aria-hidden="true">↗</span></a></div></section>
      <section id="visit" className={styles.visit}><div><p className={styles.eyebrow}>04 / Come and find us</p><h2>See you<br /><em>on the quayside.</em></h2><a className={styles.textLink} href={directions} target="_blank" rel="noreferrer">Open in Google Maps ↗</a></div><div className={styles.visitDetails}><div><h3>Our address</h3><address>Lowry’s at the Chandlery<br />2 The Chandlery, Quayside<br />Berwick-upon-Tweed<br />TD15 1HE</address></div><div><h3>Opening hours</h3><p>For this preview, hours are awaiting confirmation.<br />Please call the café before travelling.</p></div><div><h3>Get in touch</h3><a href="tel:+441289309327">01289 309327</a><a href="mailto:lowryschandlery@gmail.com">lowryschandlery@gmail.com</a></div><div><h3>Before your visit</h3><p>Please contact Lowry’s directly about dietary requirements, access, dogs or group visits.</p></div></div></section>
    </main>
    <footer className={styles.footer}><div className={styles.footerBrand}>Lowry’s<span>AT THE CHANDLERY · BERWICK-UPON-TWEED</span></div><div id="concept-notes" className={styles.notes}><div><h2>A first look, prepared for Lowry’s.</h2><p>This is an independent design concept by Atheus, not Lowry’s official website. Copy and operational details are proposed and subject to the café’s approval. No orders or bookings are taken here.</p><p>Photographs show the local setting at the dates stated, not the current café interior or food. The finished site would use Lowry’s approved photography and menu.</p></div><div><h2>Photography credits</h2><p><a href="https://www.geograph.org.uk/photo/7513947">The Chandlery, Quayside</a> © Geoff Holland (2023).<br /><a href="https://commons.wikimedia.org/wiki/File:Quayside_buildings,_Berwick-upon-Tweed_-_geograph.org.uk_-_5796983.jpg">Quayside buildings, Berwick-upon-Tweed</a> © Jonathan Hutchins (2018).</p><p>Both used under <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA 2.0</a>. Display crops and responsive resizing; photographic adaptations remain under the same licence. No endorsement implied.</p></div></div><div className={styles.footerLine}><span>DESIGN CONCEPT / SEPTEMBER 2026</span><a href="https://www.atheus.dev">Designed by ATHEUS ↗</a></div></footer>
    <nav className={styles.mobileActions} aria-label="Quick visit actions"><a href="#menu">Menu</a><a href={directions} target="_blank" rel="noreferrer">Directions ↗</a><a href="tel:+441289309327">Call</a></nav>
  </div>;
}
